In [1]:
import torch
import numpy as np
torch.__version__

'2.4.0+cu121'

In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [3]:
scalar = torch.tensor(5)
scalar

tensor(5)

In [4]:
scalar.ndim

0

In [5]:
vector = torch.tensor([4,5])
vector

tensor([4, 5])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
float_tensor = torch.tensor([[4,7,4],
                      [2,5,4],
                      [2,5,6]])
float_tensor.shape

torch.Size([3, 3])

In [9]:
TENSOR = torch.tensor([[[1,2],
                        [2,41],
                        [21,4],
                        [212,1]],[
                        [1,2],
                        [2,41],
                        [21,4],
                        [212,1]]])

TENSOR

tensor([[[  1,   2],
         [  2,  41],
         [ 21,   4],
         [212,   1]],

        [[  1,   2],
         [  2,  41],
         [ 21,   4],
         [212,   1]]])

In [10]:
# RANDOM = torch.rand(963 ,850,440,328)   #!
# RANDOM

In [11]:
random_image_size_tensor = torch.rand(size=(3, 224, 244)) # color channels, width, height
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 244]), 3)

In [12]:
zeros = torch.ones(size=(4,4))
zeros

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [13]:
pablo = torch.rand(4,4)
zeros*pablo

tensor([[0.8266, 0.6173, 0.4084, 0.0058],
        [0.2463, 0.6479, 0.5386, 0.5571],
        [0.8531, 0.6352, 0.0107, 0.8511],
        [0.6068, 0.9350, 0.0329, 0.3693]])

In [14]:
torch.arange(10,20)

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
one_to_ten = torch.arange(start=1,end=11)

zeros_one_to_ten_like = torch.zeros_like(one_to_ten)
zeros_one_to_ten_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
float_tensor = torch.tensor([[1,4],
                            [1,5]],
                            dtype=None,
                            device=None,
                            requires_grad=False)
float_tensor

tensor([[1, 4],
        [1, 5]])

In [17]:
%%time
value = 0
for i in range(len(float_tensor)):
  value+= float_tensor[i]*float_tensor[i]
value

CPU times: user 1.43 ms, sys: 79 µs, total: 1.51 ms
Wall time: 8.19 ms


tensor([ 2, 41])

In [18]:
%%time
torch.matmul(float_tensor, float_tensor)

CPU times: user 1.45 ms, sys: 82 µs, total: 1.53 ms
Wall time: 5.26 ms


tensor([[ 5, 24],
        [ 6, 29]])

In [19]:
tensor1 = torch.rand(3,4)
tensor2 = torch.rand(3,4)

torch.matmul(tensor1, tensor2.T)

tensor([[0.6881, 1.3393, 1.4275],
        [0.6230, 1.5454, 1.1048],
        [0.4355, 1.1976, 0.9539]])

In [20]:
x = torch.arange(0, 100, 10)
x.type(dtype=torch.float16).mean()
x.max()

tensor(90)

In [21]:
x.argmin()

tensor(0)

In [22]:
x.argmax()

tensor(9)

In [23]:
tensor = torch.tensor([1, 2, 3, 4, 5, 6])

tensor.reshape(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [24]:
z = tensor.view(2,3)
tensor,z

(tensor([1, 2, 3, 4, 5, 6]),
 tensor([[1, 2, 3],
         [4, 5, 6]]))

In [25]:
z[:, 0] = 4
tensor,z

(tensor([4, 2, 3, 4, 5, 6]),
 tensor([[4, 2, 3],
         [4, 5, 6]]))

In [26]:
stacked_tensor = torch.stack([z, z, z,z,z,z,z,z,z,z,z,z,z], dim=2)
stacked_tensor

tensor([[[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
         [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
         [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]],

        [[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
         [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
         [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6]]])

In [27]:
tensor1 = torch.tensor([[1.,2.,3.,2.,13.,135.]])
tensor1.shape

torch.Size([1, 6])

In [28]:
tensor1_squeezed = tensor1.squeeze().unsqueeze(dim=1)
tensor1.shape, tensor1_squeezed.shape

(torch.Size([1, 6]), torch.Size([6, 1]))

In [29]:
tensor1,tensor1_squeezed

(tensor([[  1.,   2.,   3.,   2.,  13., 135.]]),
 tensor([[  1.],
         [  2.],
         [  3.],
         [  2.],
         [ 13.],
         [135.]]))

In [30]:
x_original = torch.rand(3,2)
x_original.shape

torch.Size([3, 2])

In [31]:
x_original = x_original.permute(1,0)
x_original.shape

torch.Size([2, 3])

In [32]:
x_original[0]

tensor([0.3970, 0.0696, 0.2415])

In [33]:
zuleyha = torch.arange(1,10).reshape(1,3,3)
zuleyha, zuleyha.dim()

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 3)

In [34]:
zuleyha[:,0]

tensor([[1, 2, 3]])

In [35]:
zuleyha[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [36]:
x = torch.arange(1,10).reshape(shape=(1,3,3))
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [37]:
x[:,:,2]

tensor([[3, 6, 9]])

In [38]:
a = np.arange(1,11) # numpy's default value is int64
a, a+1
tensor = torch.from_numpy(a)
tensor.type(torch.int32)

tensor1 = torch.arange(1,11) # again default int64
tensor1.type()

tensor2 = torch.ones(7)
tensor2.numpy() # float 32

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [39]:
torch.manual_seed(42)
random = torch.rand(3,4)

torch.manual_seed(42)
torch.rand(3,4, 4),random


(tensor([[[0.8823, 0.9150, 0.3829, 0.9593],
          [0.3904, 0.6009, 0.2566, 0.7936],
          [0.9408, 0.1332, 0.9346, 0.5936],
          [0.8694, 0.5677, 0.7411, 0.4294]],
 
         [[0.8854, 0.5739, 0.2666, 0.6274],
          [0.2696, 0.4414, 0.2969, 0.8317],
          [0.1053, 0.2695, 0.3588, 0.1994],
          [0.5472, 0.0062, 0.9516, 0.0753]],
 
         [[0.8860, 0.5832, 0.3376, 0.8090],
          [0.5779, 0.9040, 0.5547, 0.3423],
          [0.6343, 0.3644, 0.7104, 0.9464],
          [0.7890, 0.2814, 0.7886, 0.5895]]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]))

In [42]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In PyTorch, .T is a shorthand for transposing a tensor. When you use Y.T, you are swapping the dimensions of the tensor.

Here's how it works with your example:

Original Tensor Y:

python
Copy code
Y = torch.rand(size=(1, 7))
This creates a tensor Y with shape (1, 7).

Transposing Y with Y.T:

python
Copy code
Y.T
The transpose operation will change the shape of Y from (1, 7) to (7, 1).

Matrix Multiplication:

'2.4.0+cu121'